{
 "title": "Home sensors",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "mac", "label": "mac", "query": { "query": "label_values(mac)" } }
  ]
 },
 "panels": [
  { "title": "$mac", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "mac" },
  {
   "title": "$mac temp °C",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sensor_temp_celsius{job=\"$job\", mac=\"$mac\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$mac humidity outside %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sensor_humidity_percent{job=\"$job\", mac=\"$mac\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$mac battery voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sensor_battery_volts{job=\"$job\", mac=\"$mac\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}